# Generated by Django 4.1 on 2022-10-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arvanthea', '0004_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(default='/media/images/dp/default.jpg', upload_to='images/'),
        ),
    ]
